spring:
  application:
    name: rabbitmq-integration
  rabbitmq:
    virtual-host: /
    username: guest
    password: guest
    port: 5672
    host: 192.168.1.103
#    listener:
#      simple:
#        acknowledge-mode: auto
